feat: add service page
vesoft-inc-private/nebula-dashboard pull request #5
Opened 2021-01-28 10:17 UTC by hetao92

2021-01-28 13:57 UTC, nianiaJR commented on app/assets/modules/Layout/routes.tsx
> +    path: '/service/leader-metric',
we discuss to have the same path name rule?

2021-01-28 13:57 UTC, nianiaJR commented on app/assets/modules/Layout/routes.tsx
> +const CPUStatistics = lazy(() => import('@assets/modules/CPUStatistics'));
Why your service need to compute CPU? it's device metrics

2021-01-28 14:00 UTC, nianiaJR commented on app/assets/modules/LeaderMetric/index.tsx
> +class LeaderMetric extends React.Component<IProps, IState> {
LeaderMetric is not a good name because the leader is a metric value. You can use other better name  such as LeaderDistribution

2021-01-28 14:01 UTC, nianiaJR commented on app/assets/modules/LeaderMetric/index.tsx
> +class LeaderMetric extends React.Component<IProps, IState> {
Btw，the values which called metrics can be store in prometheus. The leader value get from nebula server instead of prometheus.

2021-01-28 14:02 UTC, nianiaJR commented on app/assets/modules/PartitionMetric/index.tsx
> +class PartitionMetric extends React.Component<IProps, IState> {
PartitionMetric => PartitionDistribution

2021-01-28 14:09 UTC, nianiaJR commented on app/assets/modules/TimeSeriesMetric/index.tsx
> +class TimeSeriesMetric extends React.Component<IProps, IState> {
TimeSeriesMetric => ServerMetrics

2021-01-28 14:09 UTC, nianiaJR commented on app/assets/modules/VersionMetric/ServiceItem/index.tsx
> +import { Table } from 'antd'
VertionMetric => VersionStatistic

2021-01-28 14:11 UTC, nianiaJR commented on app/assets/modules/CellularDataStatistics/index.tsx
> +export default CellularDataStatistics
It seems no this function stat in the prd. We need to discuss

2021-01-28 14:19 UTC, nianiaJR commented on app/assets/components/Charts/AreaChart.tsx
It seems that your modifies have influence my original view style:
![image](https://user-images.githubusercontent.com/8124783/106151020-e04cbe00-61b6-11eb-8255-5dbe9bc0dcc9.png)

You need to add some `if/else` optional config to avoid this.

2021-01-28 14:20 UTC, nianiaJR requested changes
![image](https://user-images.githubusercontent.com/8124783/106151144-05413100-61b7-11eb-9734-8e7aa1c4108a.png)
style bug

2021-01-29 01:58 UTC, NicolaCage commented on app/assets/modules/VersionMetric/ServiceItem/index.less
> +}
If this is a separate less file，do not  use such a class name

2021-01-29 03:14 UTC, nianiaJR approved these changes

2021-01-29 03:15 UTC, merged